CREATE TABLE employees (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name                  VARCHAR(100)   NOT NULL,
    last_name                   VARCHAR(100)   NOT NULL,
    ssn_last_four               VARCHAR(4)     NOT NULL,
    filing_status               VARCHAR(30)    NOT NULL,
    employment_type             VARCHAR(10)    NOT NULL,
    pay_frequency                VARCHAR(15)    NOT NULL,
    annual_salary               DECIMAL(14,2),
    hourly_rate                 DECIMAL(8,2),
    active                      BOOLEAN        NOT NULL DEFAULT TRUE,
    ytd_gross_wages             DECIMAL(14,2)  NOT NULL DEFAULT 0,
    ytd_social_security_wages   DECIMAL(14,2)  NOT NULL DEFAULT 0,
    ytd_medicare_wages          DECIMAL(14,2)  NOT NULL DEFAULT 0,
    ytd_federal_withholding     DECIMAL(14,2)  NOT NULL DEFAULT 0,
    created_at                  TIMESTAMP      NOT NULL
);

CREATE TABLE pay_periods (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date  DATE      NOT NULL,
    end_date    DATE      NOT NULL,
    pay_date    DATE      NOT NULL,
    status      VARCHAR(15) NOT NULL,
    created_at  TIMESTAMP NOT NULL
);

CREATE TABLE pay_runs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_period_id  BIGINT      NOT NULL,
    status         VARCHAR(15) NOT NULL,
    triggered_at   TIMESTAMP   NOT NULL,
    completed_at   TIMESTAMP,
    CONSTRAINT uk_pay_run_period UNIQUE (pay_period_id),
    CONSTRAINT fk_pay_run_period FOREIGN KEY (pay_period_id) REFERENCES pay_periods (id)
);

CREATE TABLE pay_stubs (
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_run_id                     BIGINT        NOT NULL,
    employee_id                    BIGINT        NOT NULL,
    regular_hours                  DECIMAL(14,2) NOT NULL,
    overtime_hours                 DECIMAL(14,2) NOT NULL,
    gross_pay                      DECIMAL(14,2) NOT NULL,
    federal_withholding            DECIMAL(14,2) NOT NULL,
    social_security_employee       DECIMAL(14,2) NOT NULL,
    medicare_employee              DECIMAL(14,2) NOT NULL,
    additional_medicare_employee   DECIMAL(14,2) NOT NULL,
    social_security_employer       DECIMAL(14,2) NOT NULL,
    medicare_employer              DECIMAL(14,2) NOT NULL,
    net_pay                        DECIMAL(14,2) NOT NULL,
    created_at                     TIMESTAMP     NOT NULL,
    CONSTRAINT uk_pay_stub_run_employee UNIQUE (pay_run_id, employee_id),
    CONSTRAINT fk_pay_stub_run FOREIGN KEY (pay_run_id) REFERENCES pay_runs (id),
    CONSTRAINT fk_pay_stub_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);

CREATE TABLE ledger_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(40) NOT NULL UNIQUE,
    type          VARCHAR(15) NOT NULL,
    display_name  VARCHAR(100) NOT NULL
);

CREATE TABLE ledger_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pay_run_id    BIGINT        NOT NULL,
    employee_id   BIGINT,
    account_code  VARCHAR(40)   NOT NULL,
    debit_amount  DECIMAL(14,2) NOT NULL,
    credit_amount DECIMAL(14,2) NOT NULL,
    description   VARCHAR(255)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    CONSTRAINT fk_ledger_entry_run FOREIGN KEY (pay_run_id) REFERENCES pay_runs (id)
);

CREATE INDEX idx_pay_stubs_employee ON pay_stubs (employee_id);
CREATE INDEX idx_ledger_entries_run ON ledger_entries (pay_run_id);
CREATE INDEX idx_ledger_entries_account ON ledger_entries (account_code);
