CREATE TABLE idempotency_keys (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key       VARCHAR(255) NOT NULL,
    request_fingerprint   VARCHAR(64)  NOT NULL,
    response_status       INT,
    response_body         VARCHAR(8000),
    created_at            TIMESTAMP    NOT NULL,
    completed_at          TIMESTAMP,
    CONSTRAINT uk_idempotency_key UNIQUE (idempotency_key)
);
